"""

Regression tests for the six-qubit reference MaxCut instance.

The graph is the zero-based equivalent of the instance generated by

    Random.seed!(0)
    Graphs.erdos_renyi(6, 0.5)

in the Julia reference implementation.
"""

from itertools import product

from hamiltonian import (
    build_maxcut_hamiltonian,
    extract_hamiltonian_terms,
    maxcut_energy,
    maxcut_size,
)
from operator_pool import build_qaoa_double_pool, make_pauli_word


NUM_QUBITS = 6
REFERENCE_EDGES = [
    (0, 1),
    (0, 4),
    (1, 2),
    (2, 5),
    (3, 5),
]

EXPECTED_GROUND_STATES = {
    (0, 1, 0, 0, 1, 1),
    (1, 0, 1, 1, 0, 0),
}

TOL = 1e-12


def basis_energy(bits, coefficients, pauli_words):
    """Evaluate a diagonal Pauli Hamiltonian on a basis state."""

    energy = 0.0

    for coefficient, word in zip(coefficients, pauli_words):
        eigenvalue = 1.0

        for qubit, pauli in enumerate(word):
            if pauli == "I":
                continue
            if pauli == "Z":
                eigenvalue *= 1.0 if bits[qubit] == 0 else -1.0
                continue

            raise AssertionError(
                f"MaxCut Hamiltonian contains non-diagonal Pauli {pauli}."
            )

        energy += coefficient * eigenvalue

    return float(energy)


def test_qaoa_double_pool_matches_reference_order():
    pool = build_qaoa_double_pool(NUM_QUBITS)

    expected_names = [f"X{i}" for i in range(NUM_QUBITS)]
    expected_names.append("SUM_X")

    for i in range(NUM_QUBITS - 1):
        for j in range(i + 1, NUM_QUBITS):
            expected_names.extend(
                [
                    f"X{i}X{j}",
                    f"Y{i}Y{j}",
                    f"Y{i}Z{j}",
                    f"Z{i}Y{j}",
                ]
            )

    assert len(pool) == 67
    assert [entry["name"] for entry in pool] == expected_names


def test_operator_pool_metadata():
    pool = build_qaoa_double_pool(NUM_QUBITS)

    sum_x = pool[6]
    assert sum_x["name"] == "SUM_X"
    assert sum_x["is_global_mixer"]
    assert sum_x["support"] == set(range(NUM_QUBITS))

    for entry in pool:
        if entry["name"] == "SUM_X":
            continue

        assert not entry["is_global_mixer"]
        assert entry["pauli_word"] is not None


def test_maxcut_hamiltonian_matches_reference():
    hamiltonian = build_maxcut_hamiltonian(NUM_QUBITS, REFERENCE_EDGES)

    coefficients, pauli_words = extract_hamiltonian_terms(
        hamiltonian,
        NUM_QUBITS,
    )

    actual = dict(zip(pauli_words, coefficients))

    expected = {
        "I" * NUM_QUBITS: -2.5,
    }

    for i, j in REFERENCE_EDGES:
        word = make_pauli_word(
            NUM_QUBITS,
            {
                i: "Z",
                j: "Z",
            },
        )
        expected[word] = 0.5

    assert set(actual) == set(expected)
    assert len(actual) == 6

    for word, expected_coefficient in expected.items():
        assert abs(actual[word] - expected_coefficient) < TOL


def test_hamiltonian_energy_matches_classical_maxcut():
    hamiltonian = build_maxcut_hamiltonian(NUM_QUBITS, REFERENCE_EDGES)

    coefficients, pauli_words = extract_hamiltonian_terms(
        hamiltonian,
        NUM_QUBITS,
    )

    for bits in product((0, 1), repeat=NUM_QUBITS):
        bits = list(bits)

        cut_size = maxcut_size(bits, REFERENCE_EDGES)
        classical_energy = maxcut_energy(bits, REFERENCE_EDGES)
        hamiltonian_energy = basis_energy(
            bits,
            coefficients,
            pauli_words,
        )

        assert abs(classical_energy - hamiltonian_energy) < TOL
        assert abs(classical_energy + cut_size) < TOL


def test_reference_ground_states():
    hamiltonian = build_maxcut_hamiltonian(NUM_QUBITS, REFERENCE_EDGES)

    coefficients, pauli_words = extract_hamiltonian_terms(
        hamiltonian,
        NUM_QUBITS,
    )

    energies = {}

    for bits in product((0, 1), repeat=NUM_QUBITS):
        energies[bits] = basis_energy(
            bits,
            coefficients,
            pauli_words,
        )

    minimum_energy = min(energies.values())

    ground_states = {
        bits
        for bits, energy in energies.items()
        if abs(energy - minimum_energy) < TOL
    }

    # The reference graph is a tree with five edges, so all five
    # edges can be cut simultaneously.
    assert minimum_energy == -5.0
    assert ground_states == EXPECTED_GROUND_STATES
