"""Regression tests for the first MosaicADAPT-QAOA adaptation.

The reference data were generated by the Julia implementation on the
six-qubit MaxCut instance used throughout the validation study.
"""

import numpy as np
import pytest

from hamiltonian import build_maxcut_hamiltonian, extract_hamiltonian_terms
from kamis_mwis import solve_mwis_kamis
from mosaic_graph import build_incompatibility_graph, is_independent_set
from operator_pool import build_qaoa_double_pool
from tetris_qaoa_scoring import compute_tetris_qaoa_pool_scores


NUM_QUBITS = 6
GAMMA_0 = 0.001
GRADIENT_THRESHOLD = 1e-3
KAMIS_SEED = 42
SCORE_TOLERANCE = 1e-12

REFERENCE_EDGES = [
    (0, 1),
    (0, 4),
    (1, 2),
    (2, 5),
    (3, 5),
]

JULIA_SCORES = np.array(
    [
        0.0019999986666669337,
        0.0019999986666669337,
        0.0019999986666669337,
        0.0009999998333333417,
        0.0009999998333333417,
        0.0019999986666669337,
        0.009999994333334417,
        0.0019999986666669337,
        1.0842021724855044e-19,
        0.9999980000006667,
        0.9999980000006667,
        0.003999993333337866,
        0.0019999946666709335,
        5.4896205311551205e-18,
        1.1170349655049016e-17,
        0.002999996500001525,
        4.197269410259134e-17,
        1.3132446133162237e-17,
        3.9409505742338915e-18,
        0.0009999998333333415,
        9.89762256731645e-18,
        0.9999980000006667,
        0.9999995000000417,
        0.003999993333337867,
        2.1000528448303212e-17,
        1.0209288113256082e-17,
        2.2288143844126557e-18,
        0.0019999986666669337,
        0.0,
        0.9999980000006667,
        0.9999980000006666,
        0.002999996500001525,
        4.866227837506097e-18,
        8.986860751690516e-18,
        1.2748510711998047e-17,
        0.002999996500001525,
        0.0019999966666681833,
        3.869246503057644e-18,
        9.714500156744007e-18,
        0.003999993333337866,
        0.0019999946666709335,
        3.869246503057644e-18,
        2.8893144638204372e-18,
        0.002999996500001525,
        0.0019999966666681837,
        9.827849282285367e-18,
        5.699095499720736e-18,
        0.002999996500001525,
        2.4660408471378063e-17,
        9.167915499738694e-18,
        1.157208999010253e-17,
        0.0019999986666669337,
        1.3697099621170873e-17,
        0.9999980000006666,
        0.9999980000006667,
        0.0019999986666669337,
        8.017389120253204e-18,
        4.7644131510324485e-17,
        1.0871262146083054e-17,
        0.0009999998333333417,
        1.936705108781379e-18,
        0.9999995000000418,
        0.9999980000006667,
        0.002999996500001525,
        3.4212835355454777e-17,
        1.3442990412474059e-17,
        1.588538865131457e-17,
    ],
    dtype=float,
)

JULIA_ELIGIBLE_INDICES = [
    1,
    2,
    3,
    6,
    7,
    8,
    10,
    11,
    12,
    13,
    16,
    22,
    23,
    24,
    28,
    30,
    31,
    32,
    36,
    37,
    40,
    41,
    44,
    45,
    48,
    52,
    54,
    55,
    56,
    62,
    63,
    64,
]

JULIA_SELECTED_INDICES = [23, 31, 62]
JULIA_SELECTED_NAMES = ["Z0Y4", "Z1Y2", "Y3Z5"]
JULIA_SELECTED_SCORE_SUM = 2.99999700000075


COST_HAMILTONIAN = build_maxcut_hamiltonian(
    NUM_QUBITS,
    REFERENCE_EDGES,
)

COST_COEFFICIENTS, COST_PAULI_WORDS = extract_hamiltonian_terms(
    COST_HAMILTONIAN,
    NUM_QUBITS,
)

OPERATOR_POOL = build_qaoa_double_pool(NUM_QUBITS)


@pytest.fixture(scope="module")
def scoring_results():
    results = compute_tetris_qaoa_pool_scores(
        layers=[],
        gamma0=GAMMA_0,
        operator_pool=OPERATOR_POOL,
        n_qubits=NUM_QUBITS,
        cost_coefficients=COST_COEFFICIENTS,
        cost_pauli_words=COST_PAULI_WORDS,
    )

    return {
        entry["name"]: entry
        for entry in results
    }


def scores_in_pool_order(scoring_results):
    return np.array(
        [
            scoring_results[entry["name"]]["abs_gradient"]
            for entry in OPERATOR_POOL
        ],
        dtype=float,
    )


def eligible_results_in_pool_order(scoring_results):
    """Return threshold-passing candidates in canonical pool order."""

    return [
        scoring_results[entry["name"]]
        for entry in OPERATOR_POOL
        if scoring_results[entry["name"]]["abs_gradient"]
        >= GRADIENT_THRESHOLD
    ]


def test_candidate_scores_match_julia(scoring_results):
    assert len(OPERATOR_POOL) == 67
    assert set(scoring_results) == {
        entry["name"]
        for entry in OPERATOR_POOL
    }

    cudaq_scores = scores_in_pool_order(scoring_results)

    assert len(cudaq_scores) == len(JULIA_SCORES)
    assert np.max(np.abs(cudaq_scores - JULIA_SCORES)) < SCORE_TOLERANCE


def test_thresholded_candidate_set_matches_julia(scoring_results):
    cudaq_scores = scores_in_pool_order(scoring_results)

    eligible_indices = [
        index
        for index, score in enumerate(cudaq_scores, start=1)
        if score >= GRADIENT_THRESHOLD
    ]

    assert eligible_indices == JULIA_ELIGIBLE_INDICES


def test_kamis_selection_matches_julia(scoring_results):
    eligible_results = eligible_results_in_pool_order(scoring_results)
    graph = build_incompatibility_graph(eligible_results)

    selected_names, selected_weight = solve_mwis_kamis(
        operator_results=eligible_results,
        graph=graph,
        seed=KAMIS_SEED,
    )

    assert is_independent_set(selected_names, graph)

    pool_index_by_name = {
        entry["name"]: index
        for index, entry in enumerate(OPERATOR_POOL, start=1)
    }

    selected_indices = [
        pool_index_by_name[name]
        for name in selected_names
    ]

    assert selected_indices == JULIA_SELECTED_INDICES
    assert list(selected_names) == JULIA_SELECTED_NAMES
    assert abs(selected_weight - JULIA_SELECTED_SCORE_SUM) < 1e-10
